type HonoAppRenderOptions = {
  api: string[];
};

export function renderHonoApp(options: HonoAppRenderOptions): string {
  const imports = [
    "import { Hono } from 'hono';",
    "import { openSqliteRepository } from './sqlite.js';",
  ];
  const registrations = [];
  if (options.api.includes('rest')) {
    imports.push("import { registerDbRoutes } from './rest.js';");
    registrations.push('registerDbRoutes(app, repository);');
  }
  if (options.api.includes('graphql')) {
    imports.push("import { registerGraphqlRoutes } from './graphql.js';");
    registrations.push('registerGraphqlRoutes(app, repository);');
  }

  return `${generatedHeader()}
${imports.join('\n')}

export const repository = openSqliteRepository();
export const app = new Hono();

app.onError((error, c) => {
  const status = typeof (error as any).status === 'number' ? (error as any).status : 500;
  return c.json({
    error: {
      code: (error as any).code || 'SERVER_ERROR',
      message: error.message,
    },
  }, status as any);
});

${registrations.join('\n')}
`;
}

export function renderServerEntry(): string {
  return `${generatedHeader()}
import { serve } from '@hono/node-server';
import { app } from './app.js';

const port = Number(process.env.PORT || 3000);

serve({
  fetch: app.fetch,
  port,
});

console.log('db Hono API listening on http://127.0.0.1:' + port);
`;
}

function generatedHeader(comment = '//'): string {
  return `${comment} This file is generated by db. Edit it freely after generation.\n`;
}
