type HonoGraphqlProject = {
  schema: {
    graphql?: string;
  };
};

export function renderGraphqlRoutes(project: HonoGraphqlProject): string {
  return `${generatedHeader()}
import type { Hono } from 'hono';
import { executeGraphql } from '@async/db';
import type { DbRepository } from './repository.js';

const graphqlSdl = ${JSON.stringify(project.schema.graphql)};

export function registerGraphqlRoutes(app: Hono, repository: DbRepository, path = '/graphql') {
  app.get(path, (c) => c.text(graphqlSdl));
  app.post(path, async (c) => executeGraphql(createDbFacade(repository), await c.req.json()).then((result) => c.json(result)));
}

function createDbFacade(repository: DbRepository) {
  return {
    resources: new Map(Object.entries(repository.resources)),
    collection(name: string) {
      return repository.collection(name);
    },
    document(name: string) {
      const document = repository.document(name);
      return {
        all: () => document.all(),
        update: (patch: Record<string, unknown>) => document.patch(patch),
        put: (value: Record<string, unknown>) => document.put(value),
        async set(path: DbPath, value: unknown) {
          const current = await document.all();
          setPath(current, path, value);
          await document.put(current);
          return value;
        },
      };
    },
  };
}

type DbPath = string | Array<string | number>;

function setPath(document: Record<string, unknown> | unknown[], path: DbPath, value: unknown) {
  const parts = parsePath(path);
  if (parts.length === 0) {
    throw new Error('Cannot set the root document with set(). Use put(value) instead.');
  }

  let current = document as Record<string | number, unknown>;
  for (let index = 0; index < parts.length - 1; index += 1) {
    const part = parts[index];
    const nextPart = parts[index + 1];
    if (!isJsonContainer(current[part])) {
      current[part] = isArrayIndexSegment(nextPart) ? [] : {};
    }
    current = current[part] as Record<string | number, unknown>;
  }
  current[parts.at(-1) as string | number] = value;
}

function parsePath(path: DbPath): Array<string | number> {
  if (Array.isArray(path)) {
    return path.map((segment) => typeof segment === 'number' ? segment : assertSafePathSegment(segment));
  }

  if (!path || path === '/') {
    return [];
  }

  if (!path.startsWith('/')) {
    return [assertSafePathSegment(path)];
  }

  return path
    .slice(1)
    .split('/')
    .filter(Boolean)
    .map((part) => assertSafePathSegment(part.replaceAll('~1', '/').replaceAll('~0', '~')));
}

function assertSafePathSegment(segment: string): string {
  if (segment === '__proto__' || segment === 'prototype' || segment === 'constructor') {
    throw new Error(\`Unsafe document path segment "\${segment}".\`);
  }
  return segment;
}

function isJsonContainer(value: unknown): value is Record<string, unknown> | unknown[] {
  return Boolean(value) && typeof value === 'object';
}

function isArrayIndexSegment(segment: string | number): boolean {
  return typeof segment === 'number' || /^(0|[1-9]\\d*)$/.test(segment);
}
`;
}

function generatedHeader(comment = '//'): string {
  return `${comment} This file is generated by db. Edit it freely after generation.\n`;
}
