type HonoReadmeResource = {
  name: string;
  kind: string;
};

type HonoReadmeProject = {
  resources: HonoReadmeResource[];
};

type HonoReadmeOptions = {
  api: string[];
  seed: unknown;
};

export function renderReadme(project: HonoReadmeProject, options: HonoReadmeOptions): string {
  const apiText = options.api.length === 0 ? 'SQLite repository only' : options.api.join(' + ');
  return `${generatedHeader()}# db Hono API Starter

Generated from db schema resources:

${project.resources.map((resource) => `- ${resource.name} (${resource.kind})`).join('\n')}

## Shape

- API: ${apiText}
- Database: SQLite with node:sqlite
- Runtime: Node.js >=22.13
- Seed data files: ${options.seed === 'fixtures' ? 'enabled' : 'disabled'}

## Commands

\`\`\`bash
pnpm install
pnpm run dev
\`\`\`

The initial migration is in \`migrations/0001_initial.sql\`. Destructive schema changes should be reviewed manually.
`;
}

function generatedHeader(comment = '//'): string {
  return `${comment} This file is generated by db. Edit it freely after generation.\n`;
}
