/* eslint-disable */
// This file is generated by jsondb. Do not edit by hand.

export type PostStatus = "draft" | "published";

export type Post = {
  /** Stable post id. */
  id: string;
  /** Post title shown in lists. */
  title: string;
  /** User id for the author. */
  authorId: string;
  status?: PostStatus;
};

export type User = {
  /** Stable user id. */
  id: string;
  /** Display name shown beside authored content. */
  name: string;
  /** Author email address. */
  email: string;
};

export type JsonDbCollections = {
  posts: Post;
  users: User;
};

export type JsonDbDocuments = {
};

export type JsonDbTypes = {
  collections: JsonDbCollections;
  documents: JsonDbDocuments;
};

export type JsonDbCollectionName = keyof JsonDbCollections;
export type JsonDbDocumentName = keyof JsonDbDocuments;
