import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import { promisify } from 'node:util';
import { loadConfig } from '../config.js';
import { generateHonoStarter, renderHonoStarter } from './hono.js';
import { makeProject, writeConfig, writeFixture } from '../../test/helpers.js';

const execFileAsync = promisify(execFile);

function generatedFileContent(files: Array<{ path: string; content: string }>, filePath: string): string {
  const file = files.find((candidate) => candidate.path === filePath);
  assert(file, `expected generated file ${filePath}`);
  return file.content;
}

test('render hono starter locks the standalone REST GraphQL fixture seed contract', () => {
  const files = renderHonoStarter({
    diagnostics: [],
    resources: [
      {
        name: 'users',
        kind: 'collection',
        idField: 'id',
        fields: {
          id: { type: 'string', required: true },
          email: { type: 'string', required: true },
          role: { type: 'enum', values: ['admin', 'user'], default: 'user' },
        },
        seed: [{ id: 'u_1', email: 'ada@example.com' }],
      },
      {
        name: 'settings',
        kind: 'document',
        fields: {
          theme: { type: 'string', default: 'light' },
        },
        seed: { theme: 'dark' },
      },
    ],
    schema: {
      resources: {
        users: {
          name: 'users',
          kind: 'collection',
          routePath: '/users',
          idField: 'id',
          fields: {
            id: { type: 'string', required: true },
            email: { type: 'string', required: true },
            role: { type: 'enum', values: ['admin', 'user'], default: 'user' },
          },
        },
        settings: {
          name: 'settings',
          kind: 'document',
          routePath: '/settings',
          fields: {
            theme: { type: 'string', default: 'light' },
          },
        },
      },
      graphql: 'type User { id: String! email: String! }',
    },
  }, {
    api: ['rest', 'graphql'],
    seed: 'fixtures',
    app: 'standalone',
  });

  assert.deepEqual(files.map((file) => file.path).sort(), [
    'README.md',
    'migrations/0001_initial.sql',
    'package.json',
    'src/app.ts',
    'src/graphql.ts',
    'src/repository.ts',
    'src/rest.ts',
    'src/schema.ts',
    'src/seed.ts',
    'src/server.ts',
    'src/sqlite.ts',
    'src/validators.ts',
    'tsconfig.json',
  ]);

  const appSource = generatedFileContent(files, 'src/app.ts');
  assert.match(appSource, /import \{ registerDbRoutes \} from '\.\/rest\.js';/);
  assert.match(appSource, /import \{ registerGraphqlRoutes \} from '\.\/graphql\.js';/);
  assert.match(appSource, /export const repository = openSqliteRepository\(\);/);
  assert.match(appSource, /registerDbRoutes\(app, repository\);/);
  assert.match(appSource, /registerGraphqlRoutes\(app, repository\);/);

  const graphqlSource = generatedFileContent(files, 'src/graphql.ts');
  assert.match(graphqlSource, /import \{ executeGraphql \} from '@async\/db';/);
  assert.match(graphqlSource, /const graphqlSdl = "type User \{ id: String! email: String! \}";/);
  assert.match(graphqlSource, /app\.post\(path, async \(c\) => executeGraphql\(createDbFacade\(repository\), await c\.req\.json\(\)\)/);

  const restSource = generatedFileContent(files, 'src/rest.ts');
  assert.match(restSource, /app\.get\(resource\.routePath, async \(c\) => c\.json\(await repository\.collection\(resourceName\)\.all\(\)\)\);/);
  assert.match(restSource, /app\.patch\(resource\.routePath \+ '\/:id', async \(c\) => \{/);
  assert.match(restSource, /app\.put\(resource\.routePath, async \(c\) => c\.json\(await repository\.document\(resourceName\)\.put\(await c\.req\.json\(\)\)\)\);/);

  const schemaSource = generatedFileContent(files, 'src/schema.ts');
  assert.match(schemaSource, /export const resources = \{/);
  assert.match(schemaSource, /"users": \{/);
  assert.match(schemaSource, /export const seedData = \{/);
  assert.match(schemaSource, /"settings": \{/);

  const sqliteSource = generatedFileContent(files, 'src/sqlite.ts');
  assert.match(sqliteSource, /import \{ seedData \} from '\.\/schema\.js';/);
  assert.match(sqliteSource, /migrate\(db\);\n  seedFixtures\(db\);/);
  assert.match(sqliteSource, /function seedFixtures\(db: DatabaseSync\) \{/);
  assert.match(sqliteSource, /CREATE TABLE IF NOT EXISTS \\"_db_documents\\"/);

  const migration = generatedFileContent(files, 'migrations/0001_initial.sql');
  assert.match(migration, /CREATE TABLE IF NOT EXISTS "users"/);
  assert.match(migration, /"id" TEXT PRIMARY KEY/);
  assert.match(migration, /"email" TEXT NOT NULL/);
  assert.match(migration, /CREATE TABLE IF NOT EXISTS "_db_documents"/);

  assert.equal(generatedFileContent(files, 'src/seed.ts'), [
    '// This file is generated by db. Edit it freely after generation.',
    '',
    "export { seedData } from './schema.js';",
    '',
  ].join('\n'));
});

test('generate hono creates a REST standalone SQLite starter from schema fixtures', async () => {
  const cwd = await makeProject();
  await writeFixture(cwd, 'users.schema.jsonc', `{
    "kind": "collection",
    "idField": "id",
    "fields": {
      "id": { "type": "string", "required": true },
      "email": { "type": "string", "required": true },
      "role": {
        "type": "enum",
        "values": ["admin", "user"],
        "default": "user"
      },
      "profile": {
        "type": "object",
        "fields": {
          "title": { "type": "string" }
        }
      }
    },
    "seed": []
  }`);

  const config = await loadConfig({ cwd });
  const result = await generateHonoStarter(config, {
    outDir: './server',
  });

  const relativeFiles = result.files.map((file) => path.relative(cwd, file)).sort();
  assert.deepEqual(relativeFiles, [
    'server/README.md',
    'server/migrations/0001_initial.sql',
    'server/package.json',
    'server/src/app.ts',
    'server/src/repository.ts',
    'server/src/rest.ts',
    'server/src/schema.ts',
    'server/src/server.ts',
    'server/src/sqlite.ts',
    'server/src/validators.ts',
    'server/tsconfig.json',
  ]);

  assert.match(await readFile(path.join(cwd, 'server/package.json'), 'utf8'), /"hono"/);
  assert.match(await readFile(path.join(cwd, 'server/package.json'), 'utf8'), /">=22\.13"/);
  assert.match(await readFile(path.join(cwd, 'server/src/rest.ts'), 'utf8'), /registerDbRoutes/);
  const sqliteSource = await readFile(path.join(cwd, 'server/src/sqlite.ts'), 'utf8');
  assert.match(sqliteSource, /node:sqlite/);
  assert.match(sqliteSource.slice(
    sqliteSource.indexOf('async create(record)'),
    sqliteSource.indexOf('async patch(id, patch)'),
  ), /const next = applyDefaults\(resourceName, stripUnknownFields/);
  assert.match(sqliteSource.slice(
    sqliteSource.indexOf('async patch(id, patch)'),
    sqliteSource.indexOf('async delete(id)'),
  ), /const next = stripUnknownFields\(resourceName,/);
  assert.doesNotMatch(sqliteSource.slice(
    sqliteSource.indexOf('async patch(id, patch)'),
    sqliteSource.indexOf('async delete(id)'),
  ), /applyDefaults/);
  assert.doesNotMatch(sqliteSource.slice(
    sqliteSource.indexOf('async put(value)'),
    sqliteSource.indexOf('async patch(value)'),
  ), /applyDefaults/);
  assert.match(await readFile(path.join(cwd, 'server/migrations/0001_initial.sql'), 'utf8'), /CREATE TABLE IF NOT EXISTS "users"/);
  assert.match(await readFile(path.join(cwd, 'server/migrations/0001_initial.sql'), 'utf8'), /"id" TEXT PRIMARY KEY/);
  assert.match(await readFile(path.join(cwd, 'server/migrations/0001_initial.sql'), 'utf8'), /"profile" TEXT/);
});

test('generate hono can emit REST plus GraphQL and fixture seeding', async () => {
  const cwd = await makeProject();
  await writeFixture(cwd, 'users.json', JSON.stringify([
    {
      id: 'u_1',
      email: 'ada@example.com',
    },
  ]));
  await writeFixture(cwd, 'settings.json', JSON.stringify({
    theme: 'dark',
  }));

  const config = await loadConfig({ cwd });
  await generateHonoStarter(config, {
    outDir: './api',
    api: 'rest,graphql',
    seed: 'fixtures',
  });

  assert.match(await readFile(path.join(cwd, 'api/src/graphql.ts'), 'utf8'), /executeGraphql/);
  assert.match(await readFile(path.join(cwd, 'api/src/app.ts'), 'utf8'), /registerDbRoutes/);
  assert.match(await readFile(path.join(cwd, 'api/src/app.ts'), 'utf8'), /registerGraphqlRoutes/);
  assert.match(await readFile(path.join(cwd, 'api/src/sqlite.ts'), 'utf8'), /seedFixtures/);
  assert.match(await readFile(path.join(cwd, 'api/package.json'), 'utf8'), /"@async\/db": "\^0\.1\.0"/);
});

test('generate hono can emit SQLite-only module output', async () => {
  const cwd = await makeProject();
  await writeFixture(cwd, 'users.json', JSON.stringify([{ id: 'u_1', name: 'Ada' }]));

  const config = await loadConfig({ cwd });
  const result = await generateHonoStarter(config, {
    outDir: './db-core',
    api: 'none',
    app: 'module',
  });
  const relativeFiles = result.files.map((file) => path.relative(cwd, file)).sort();

  assert.equal(relativeFiles.includes('db-core/src/app.ts'), false);
  assert.equal(relativeFiles.includes('db-core/src/rest.ts'), false);
  assert.equal(relativeFiles.includes('db-core/package.json'), false);
  assert.equal(relativeFiles.includes('db-core/src/sqlite.ts'), true);
  assert.equal(relativeFiles.includes('db-core/src/repository.ts'), true);
});

test('generate hono blocks schema warnings unless explicitly allowed', async () => {
  const cwd = await makeProject();
  await writeFixture(cwd, 'users.json', JSON.stringify([
    {
      id: 'u_1',
      email: 'ada@example.com',
      twitterHandle: '@ada',
    },
  ]));
  await writeFixture(cwd, 'users.schema.jsonc', `{
    "kind": "collection",
    "idField": "id",
    "fields": {
      "id": { "type": "string", "required": true },
      "email": { "type": "string", "required": true }
    }
  }`);

  const config = await loadConfig({ cwd });
  await assert.rejects(
    () => generateHonoStarter(config, { outDir: './blocked' }),
    /schema diagnostics are present/,
  );

  const result = await generateHonoStarter(config, {
    outDir: './allowed',
    allowWarnings: true,
  });
  assert.equal(result.diagnostics.some((diagnostic) => diagnostic.code === 'SCHEMA_UNKNOWN_FIELD'), true);
});

test('async-db generate hono CLI writes generated files', async () => {
  const cwd = await makeProject();
  await writeConfig(cwd, `export default {
    generate: {
      hono: {
        outDir: './generated-api',
        api: ['rest'],
        app: 'standalone'
      }
    }
  };`);
  await writeFixture(cwd, 'users.json', JSON.stringify([{ id: 'u_1', name: 'Ada' }]));

  const { stdout } = await execFileAsync(process.execPath, [
    path.resolve('dist/cli.js'),
    'generate',
    'hono',
    '--cwd',
    cwd,
  ]);

  assert.match(stdout, /Generated generated-api\/src\/sqlite\.ts/);
  assert.match(await readFile(path.join(cwd, 'generated-api/src/rest.ts'), 'utf8'), /registerDbRoutes/);
});
