/* eslint-disable */
// This file is generated by jsondb. Do not edit by hand.

export type UserRole = "admin" | "user";

export type Project = {
  id: string;
  name: string;
  metadata?: Record<string, unknown>;
};

export type User = {
  id: string;
  name: string;
  email: string;
  role?: UserRole;
};

export type JsonDbCollections = {
  projects: Project;
  users: User;
};

export type JsonDbDocuments = {
};

export type JsonDbTypes = {
  collections: JsonDbCollections;
  documents: JsonDbDocuments;
};

export type JsonDbCollectionName = keyof JsonDbCollections;
export type JsonDbDocumentName = keyof JsonDbDocuments;
