/* eslint-disable */
// This file is generated by jsondb. Do not edit by hand.

export type ProjectStatus = "planned" | "active" | "paused" | "done";

export type UserRole = "admin" | "editor" | "user";

export type Project = {
  id: string;
  name: string;
  ownerId: string;
  status?: ProjectStatus;
  metadata?: {
    priority?: string;
  };
};

export type Settings = {
  features?: {
    billing?: boolean;
    graphql?: boolean;
  };
  locale?: string;
  theme?: string;
};

/** Users who can sign into the local test app. */
export type User = {
  /** Stable user id. */
  id: string;
  /** Display name shown in the UI. */
  name: string;
  /** Unique email address. */
  email: string;
  /** Local authorization role. */
  role?: UserRole;
  /** Optional social handle used by local profile demos. */
  twitterHandle?: string;
  profile?: {
    title?: string;
    location?: string;
  };
};

export type JsonDbCollections = {
  projects: Project;
  users: User;
};

export type JsonDbDocuments = {
  settings: Settings;
};

export type JsonDbTypes = {
  collections: JsonDbCollections;
  documents: JsonDbDocuments;
};

export type JsonDbCollectionName = keyof JsonDbCollections;
export type JsonDbDocumentName = keyof JsonDbDocuments;
