/* eslint-disable */
// This file is generated by jsondb. Do not edit by hand.

export type ProjectStatus = "planned" | "active" | "paused" | "done";

/** Projects used to demonstrate generated form metadata. */
export type Project = {
  /** Stable project id. */
  id: string;
  /** Project display name. */
  name: string;
  /** Owner user id. */
  ownerId: string;
  /** Workflow status for local admin forms. */
  status?: ProjectStatus;
  /** Internal project notes. */
  notes?: string;
};

/** People who can own local projects. */
export type User = {
  /** Stable user id. */
  id: string;
  /** Display name. */
  name: string;
  /** Email shown in admin forms. */
  email: string;
  /** Markdown biography for profile previews. */
  bio?: string;
};

export type JsonDbCollections = {
  projects: Project;
  users: User;
};

export type JsonDbDocuments = {
};

export type JsonDbTypes = {
  collections: JsonDbCollections;
  documents: JsonDbDocuments;
};

export type JsonDbCollectionName = keyof JsonDbCollections;
export type JsonDbDocumentName = keyof JsonDbDocuments;
