/* eslint-disable */
// This file is generated by jsondb. Do not edit by hand.

export type Post = {
  authorId: string;
  id: string;
  published: boolean;
  tags: Array<string>;
  title: string;
};

export type Settings = {
  features?: {
    billing?: boolean;
    graphql?: boolean;
  };
  locale?: string;
  theme?: string;
};

export type User = {
  email: string;
  id: string;
  name: string;
  role: string;
};

export type JsonDbCollections = {
  posts: Post;
  users: User;
};

export type JsonDbDocuments = {
  settings: Settings;
};

export type JsonDbTypes = {
  collections: JsonDbCollections;
  documents: JsonDbDocuments;
};

export type JsonDbCollectionName = keyof JsonDbCollections;
export type JsonDbDocumentName = keyof JsonDbDocuments;
