/* eslint-disable */
// This file is generated by jsondb. Do not edit by hand.

export type Customer = {
  active: boolean;
  customerId: string;
  email: string;
  name: string;
  plan: string;
  postalCode: string;
  signupScore: number;
};

export type JsonDbCollections = {
  customers: Customer;
};

export type JsonDbDocuments = {
};

export type JsonDbTypes = {
  collections: JsonDbCollections;
  documents: JsonDbDocuments;
};

export type JsonDbCollectionName = keyof JsonDbCollections;
export type JsonDbDocumentName = keyof JsonDbDocuments;
