/* eslint-disable */
// This file is generated by jsondb. Do not edit by hand.

export type PageVisibility = "public" | "private";

export type UserRole = "admin" | "user";

export type Page = {
  /** Stable page id used in routes and links. */
  id: string;
  /** Human-readable page title. */
  title: string;
  /** Whether the page can be shown publicly. */
  visibility?: PageVisibility;
  /** Short markdown-like page body for the demo. */
  body?: string;
  /** Timestamp assigned by the pages create hook. */
  createdAt?: string;
  /** Timestamp assigned by the shared write hook. */
  updatedAt?: string;
};

export type User = {
  /** Stable user id. */
  id: string;
  /** Display name shown in the app. */
  name: string;
  /** Email address used for local sign-in. */
  email: string;
  /** Local authorization role. */
  role?: UserRole;
};

export type JsonDbCollections = {
  pages: Page;
  users: User;
};

export type JsonDbDocuments = {
};

export type JsonDbTypes = {
  collections: JsonDbCollections;
  documents: JsonDbDocuments;
};

export type JsonDbCollectionName = keyof JsonDbCollections;
export type JsonDbDocumentName = keyof JsonDbDocuments;
