/* eslint-disable */
// This file is generated by jsondb. Do not edit by hand.

export type UserRole = "admin" | "user";

export type Settings = {
  itemsPerPage?: number;
  showBetaFeatures?: boolean;
  theme?: string;
};

export type User = {
  /** Stable user id. */
  id: string;
  /** Display name shown in the app. */
  name: string;
  /** Email address used for local sign-in. */
  email: string;
  /** Local authorization role. */
  role?: UserRole;
};

export type JsonDbCollections = {
  users: User;
};

export type JsonDbDocuments = {
  settings: Settings;
};

export type JsonDbTypes = {
  collections: JsonDbCollections;
  documents: JsonDbDocuments;
};

export type JsonDbCollectionName = keyof JsonDbCollections;
export type JsonDbDocumentName = keyof JsonDbDocuments;
