/* eslint-disable */
// This file is generated by jsondb. Do not edit by hand.

export type PageStatus = "draft" | "review" | "published";

/** CMS pages rendered by a tiny schema-driven UI example. */
export type Page = {
  /** Stable page id. */
  id: string;
  /** Page title shown in the CMS list. */
  title: string;
  /** Publication state. */
  status?: PageStatus;
  /** Page author. */
  authorId: string;
  /** Short page summary. */
  summary?: string;
  /** Markdown body content. */
  bodyMarkdown?: string;
};

/** Authors that can own CMS pages. */
export type User = {
  /** Stable author id. */
  id: string;
  /** Author display name. */
  name: string;
  /** Author email address. */
  email: string;
};

export type JsonDbCollections = {
  pages: Page;
  users: User;
};

export type JsonDbDocuments = {
};

export type JsonDbTypes = {
  collections: JsonDbCollections;
  documents: JsonDbDocuments;
};

export type JsonDbCollectionName = keyof JsonDbCollections;
export type JsonDbDocumentName = keyof JsonDbDocuments;
