import path from 'node:path';
import { writeText } from './fs-utils.js';
import { pascalCase } from './names.js';
import { loadProjectSchema } from './schema.js';

export async function generateTypes(config, options = {}) {
  const project = options.project ?? await loadProjectSchema(config);
  const content = renderTypes(project.resources, config);
  const outFiles = outputFiles(config, options);

  for (const outFile of outFiles) {
    await writeText(outFile, content);
  }

  return {
    content,
    outFiles,
    diagnostics: project.diagnostics,
  };
}

export function renderTypes(resources, config) {
  const lines = [
    '/* eslint-disable */',
    '// This file is generated by db. Do not edit by hand.',
    '',
  ];

  const enumAliases = collectEnumAliases(resources);
  for (const alias of enumAliases) {
    lines.push(renderEnumAlias(alias), '');
  }

  const variantAliases = collectVariantAliases(resources);
  for (const alias of variantAliases) {
    lines.push(...renderVariantAlias(alias, config), '');
  }

  for (const resource of resources) {
    if (resource.description && config.types?.emitComments !== false) {
      lines.push(jsDoc(resource.description));
    }

    lines.push(`export type ${resource.typeName} = {`);
    const fieldEntries = Object.entries(resource.fields ?? {});
    if (fieldEntries.length === 0 && resource.typeFallback === 'record') {
      lines.push('  [key: string]: unknown;');
    } else {
      for (const [fieldName, field] of fieldEntries) {
        const fieldLines = renderField(fieldName, field, resource, config, 1);
        lines.push(...fieldLines);
      }
    }
    lines.push('};', '');
  }

  const collectionResources = resources.filter((resource) => resource.kind === 'collection');
  const documentResources = resources.filter((resource) => resource.kind === 'document');

  lines.push('export type DbCollections = {');
  for (const resource of collectionResources) {
    lines.push(`  ${propertyName(resource.name)}: ${resource.typeName};`);
  }
  lines.push('};', '');

  lines.push('export type DbDocuments = {');
  for (const resource of documentResources) {
    lines.push(`  ${propertyName(resource.name)}: ${resource.typeName};`);
  }
  lines.push('};', '');

  lines.push('export type DbTypes = {');
  lines.push('  collections: DbCollections;');
  lines.push('  documents: DbDocuments;');
  lines.push('};');

  if (config.types?.exportRuntimeHelpers !== false) {
    lines.push('', 'export type DbCollectionName = keyof DbCollections;', 'export type DbDocumentName = keyof DbDocuments;');
  }

  return `${lines.join('\n')}\n`;
}

function outputFiles(config, options) {
  const outFiles = [];
  if (options.outFile) {
    outFiles.push(path.resolve(config.cwd, options.outFile));
    return unique(outFiles);
  }

  if (config.types?.outFile) {
    outFiles.push(config.types.outFile);
  }

  if (config.types?.commitOutFile) {
    outFiles.push(config.types.commitOutFile);
  }

  return unique(outFiles);
}

function renderField(fieldName, field, resource, config, depth, fieldPath = fieldName) {
  const lines = [];
  const indent = '  '.repeat(depth);

  if (field.description && config.types?.emitComments !== false) {
    lines.push(`${indent}${jsDoc(field.description, depth)}`);
  }

  const readonly = config.types?.useReadonly ? 'readonly ' : '';
  const optional = field.required ? '' : '?';
  lines.push(`${indent}${readonly}${propertyName(fieldName)}${optional}: ${typeForField(field, fieldPath, resource, config, depth)};`);

  return lines;
}

function typeForField(field, fieldPath, resource, config, depth) {
  let type;
  switch (field.type) {
    case 'string':
    case 'datetime':
      type = 'string';
      break;
    case 'number':
      type = 'number';
      break;
    case 'boolean':
      type = 'boolean';
      break;
    case 'enum':
      type = enumAliasName(resource, fieldPath);
      break;
    case 'array':
      type = `Array<${typeForField(field.items ?? { type: 'unknown' }, `${fieldPath}Item`, resource, config, depth)}>`;
      break;
    case 'object':
      type = field.variants
        ? variantAliasName(resource, fieldPath)
        : objectType(field, resource, config, depth, fieldPath);
      break;
    case 'unknown':
    default:
      type = 'unknown';
  }

  return field.nullable ? `${type} | null` : type;
}

function objectType(field, resource, config, depth, fieldPath) {
  const fields = field.fields ?? {};
  const entries = Object.entries(fields);

  if (entries.length === 0) {
    return 'Record<string, unknown>';
  }

  const indent = '  '.repeat(depth);
  const childIndent = '  '.repeat(depth + 1);
  const readonly = config.types?.useReadonly ? 'readonly ' : '';
  const lines = ['{'];
  for (const [fieldName, childField] of entries) {
    if (childField.description && config.types?.emitComments !== false) {
      lines.push(`${childIndent}${jsDoc(childField.description, depth + 1)}`);
    }

    const optional = childField.required ? '' : '?';
    lines.push(`${childIndent}${readonly}${propertyName(fieldName)}${optional}: ${typeForField(childField, `${fieldPath}${pascalCase(fieldName)}`, resource, config, depth + 1)};`);
  }
  if (field.additionalProperties === true) {
    lines.push(`${childIndent}[key: string]: unknown;`);
  }
  lines.push(`${indent}}`);
  return lines.join('\n');
}

function renderVariantAlias(alias, config) {
  const lines = [`export type ${alias.name} =`];
  const entries = Object.entries(alias.variants);
  for (const [index, [variantName, variant]] of entries.entries()) {
    const prefix = index === 0 ? '  |' : '  |';
    lines.push(`${prefix} ${variantObjectType(variantName, variant, alias.resource, config, alias.fieldPath, 2)}`);
  }
  return [`${lines.join('\n')};`];
}

function renderEnumAlias(alias) {
  const values = alias.values.map((value) => literalType(value));
  if (values.length <= 3) {
    return `export type ${alias.name} = ${values.join(' | ')};`;
  }

  return [
    `export type ${alias.name} =`,
    ...values.map((value) => `  | ${value}`),
  ].join('\n') + ';';
}

function variantObjectType(variantName, variant, resource, config, fieldPath, depth) {
  const fields = variant.fields ?? {};
  const indent = '  '.repeat(depth);
  const childIndent = '  '.repeat(depth + 1);
  const readonly = config.types?.useReadonly ? 'readonly ' : '';
  const lines = ['{'];
  for (const [fieldName, childField] of Object.entries(fields)) {
    if (childField.description && config.types?.emitComments !== false) {
      lines.push(`${childIndent}${jsDoc(childField.description, depth + 1)}`);
    }

    const optional = childField.required ? '' : '?';
    const childPath = `${fieldPath}${pascalCase(fieldName)}`;
    lines.push(`${childIndent}${readonly}${propertyName(fieldName)}${optional}: ${variantFieldType(childField, fieldName, variantName, resource, config, depth + 1, childPath)};`);
  }
  if (variant.additionalProperties === true) {
    lines.push(`${childIndent}[key: string]: unknown;`);
  }
  lines.push(`${indent}}`);
  return lines.join('\n');
}

function variantFieldType(field, fieldName, variantName, resource, config, depth, fieldPath) {
  if (field.type === 'enum' && field.values?.length === 1 && field.values[0] === variantName) {
    return literalType(variantName);
  }

  return typeForField(field, fieldPath, resource, config, depth);
}

function collectEnumAliases(resources) {
  const aliases = new Map();
  for (const resource of resources) {
    for (const [fieldName, field] of Object.entries(resource.fields)) {
      collectFieldEnumAliases(aliases, resource, fieldName, field);
    }
  }
  return [...aliases.values()];
}

function collectFieldEnumAliases(aliases, resource, fieldName, field) {
  if (field.type === 'enum') {
    addEnumAlias(aliases, enumAliasName(resource, fieldName), field.values ?? []);
  }

  if (field.type === 'object') {
    for (const [childName, childField] of Object.entries(field.fields ?? {})) {
      collectFieldEnumAliases(aliases, resource, `${fieldName}${pascalCase(childName)}`, childField);
    }
    for (const variant of Object.values(field.variants ?? {})) {
      for (const [childName, childField] of Object.entries(variant.fields ?? {})) {
        if (childField.type === 'enum' && childField.values?.length === 1) {
          continue;
        }
        collectFieldEnumAliases(aliases, resource, `${fieldName}${pascalCase(childName)}`, childField);
      }
    }
  }

  if (field.type === 'array' && field.items) {
    collectFieldEnumAliases(aliases, resource, `${fieldName}Item`, field.items);
  }
}

function addEnumAlias(aliases, name, values) {
  const existing = aliases.get(name);
  if (!existing) {
    aliases.set(name, {
      name,
      values: [...values],
    });
    return;
  }

  existing.values = [...new Set([...existing.values, ...values])];
}

function collectVariantAliases(resources) {
  const aliases = [];
  for (const resource of resources) {
    for (const [fieldName, field] of Object.entries(resource.fields)) {
      collectFieldVariantAliases(aliases, resource, fieldName, field);
    }
  }
  return aliases;
}

function collectFieldVariantAliases(aliases, resource, fieldName, field) {
  if (field.type === 'object' && field.variants) {
    aliases.push({
      name: variantAliasName(resource, fieldName),
      resource,
      fieldPath: fieldName,
      variants: field.variants,
    });
  }

  if (field.type === 'object') {
    for (const [childName, childField] of Object.entries(field.fields ?? {})) {
      collectFieldVariantAliases(aliases, resource, `${fieldName}${pascalCase(childName)}`, childField);
    }
    for (const variant of Object.values(field.variants ?? {})) {
      for (const [childName, childField] of Object.entries(variant.fields ?? {})) {
        collectFieldVariantAliases(aliases, resource, `${fieldName}${pascalCase(childName)}`, childField);
      }
    }
  }

  if (field.type === 'array' && field.items) {
    collectFieldVariantAliases(aliases, resource, `${fieldName}Item`, field.items);
  }
}

function enumAliasName(resource, fieldName) {
  return `${resource.typeName}${pascalCase(fieldName)}`;
}

function variantAliasName(resource, fieldName) {
  return `${resource.typeName}${pascalCase(fieldName)}`;
}

function literalType(value) {
  return JSON.stringify(value);
}

function propertyName(value) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value) ? value : JSON.stringify(value);
}

function jsDoc(text, depth = 0) {
  const indent = '  '.repeat(depth);
  const escaped = String(text).replaceAll('*/', '* /');
  return `${indent}/** ${escaped} */`.trimStart();
}

function unique(values) {
  return [...new Set(values.filter(Boolean))];
}
